### ISSUE TITLE
How to install this driver ?

### ISSUE THREAD

**Issue by kangear** [nikkov/Win-Widget#1]
Hi, I'm newbie for Windows Driver develop, I tried build this code, but not as MSVAD which is a normal windows  inf driver, I can install it with devcon. I don't know how to install Win-Widget, I can not found any *.sys file, I only found some file like below:
```
asiouac2.dll*                                   link.1872.write.1.tlog
asiouac2.dll.embed.manifest                     link.1872-cvtres.read.1.tlog
asiouac2.dll.embed.manifest.res                 link.1872-cvtres.write.1.tlog
asiouac2.dll.intermediate.manifest              link.command.1.tlog
asiouac2.exp                                    link.read.1.tlog
asiouac2.ilk                                    link.write.1.tlog
asiouac2.lastbuildstate                         link-cvtres.read.1.tlog
asiouac2.lib                                    link-cvtres.write.1.tlog
asiouac2.log                                    mt.command.1.tlog
asiouac2.obj                                    mt.read.1.tlog
asiouac2.pdb                                    mt.write.1.tlog
asiouac2.vcxprojResolveAssemblyReference.cache  rc.command.1.tlog
asiouac2.write.1.tlog                           rc.read.1.tlog
asiouac2_manifest.rc                            rc.write.1.tlog
cl.command.1.tlog                               register.obj
CL.read.1.tlog                                  uaclib.lib
CL.write.1.tlog                                 vc100.idb
combase.obj                                     vc100.pdb
dllentry.obj                                    wintimer.obj
link.1872.read.1.tlog
```

Would you like to tell me how to install it ? :)

**Comment by nikkov** [comment]
Hi,
Win-widget isn't native windows audio driver. It's ASIO driver (really just COM-object in DLL) for application with support ASIO output. You can read about installation procedure at this link: [https://www.henryaudio.com/uploads/Fact_sheet_Mk3.pdf](https://www.henryaudio.com/uploads/Fact_sheet_Mk3.pdf)

**Comment by kangear** [comment]
thanks nikkov, could this driver support a normal Usb audio (not Henry Audio USB*, such as CMedia/3system usb audio) ? I want to write a driver for usb Audio, but there is no windows's usbaudio.sys source code where I can find in the world, but I found your code, so I want to know if it support normal USB AUDIO Device and if it can be modify to support WASPAI.

**Comment by nikkov** [comment]
This code is useless for **native USB Audio**. As started point you can take the old and unfinished project from [sourceforge](https://sourceforge.net/projects/zaudiodriverwin/) but it's very very hard task
