### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by MEInC1243** [nikkov/Win-Widget#2]
Nikolay, if tou know russian - please text on it. I need help with install this driver. I search for BCA2000 drivers for win X64 and found your Git, please reply on this message something.

**Comment by nikkov** [comment]
Win-Widget это не настоящий аудио драйвер Windows, а ASIO-драйвер для Windows, причем с ограниченным функционалом. Подробности по его установке для Audio-widget устройства есть [здесь](https://github.com/borgestrand/sdr-widget/blob/audio-widget-experimental/AW_readme.txt).
Я сильно сомневаюсь, что он подойдет для BCA2000, да и в Win11 уже есть ограниченная поддержка UAC2, поэтому сейчас смысла в Win-Widget уже нет.

**Comment by MEInC1243** [comment]
СПАСИБО ОГРОМНОЕ ЗА ОТВЕТ! Итак:
1. Я использую 10 х64 поэтому не страшно что в 11 нет функционала
2. Если это ASIO драйвер - я смогу вывести звук с какого-либо ASIO совместимого приложения по типу FL Studio?
Я действительно очень благодарен за ответ, ибо имея на руках столь крутую звуковуху изза отсутствия драйверов для более менее современных систем - я получаю просто нерабочий кирпич.

**Comment by MEInC1243** [comment]
И ещё момент, AVsetup.zip нет возможности скачать ибо сайт лежит

**Comment by MEInC1243** [comment]
Я чтото вообще не понял как его установить, современные microsoft vs не понимают приложения, что прилагаются, если Вы можете - прошу уделите мне немного своего времени и помогите с установкой, мне нужно просто вывести звук, заранее спасибо!

**Comment by nikkov** [comment]
Наоборот, в Win11 расширен функционал поддержки UAC2, по сравнению с 10.
Скачать можно [здесь](https://github.com/borgestrand/widget_binaries)
К сожалению, если вывод звука не работает в Win10, то с вероятностью 99% и моя поделка не поможет. Я уже давно отошел от этой темы, а запустить драйвер для устройства отличного от Audio-Widget потребует немало усилий, поэтому помочь ничем не смогу. Тем более, что само устройство может быть нестандартным UAC2 устройством, как, например, моя e-mu 0404.
